name: Mirror
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          # Make sure an empty repo exists on all remote mirrors before adding here! 
          - awesome-safety-tools
          - community
          - coop
          - coop-integration-example
          - osprey
          - playground
    steps:
      - uses: actions/checkout@v6
        with:
          repository: roostorg/${{ matrix.repo }}
          fetch-depth: 0
      - uses: actions/checkout@v6
        with:
          repository: roostorg/mirror
          ref: ${{ github.sha }}
          path: .mirror-action

      - name: Codeberg
        uses: ./.mirror-action
        with:
          # There's something weird with Codeberg repo names; appending `-mirror` for now
          destination: https://codeberg.org/roostorg/${{ matrix.repo }}-mirror.git
          token: ${{ secrets.CODEBERG_TOKEN }}
          token_username: ${{ secrets.CODEBERG_USERNAME }}

      - name: GitLab
        uses: ./.mirror-action
        with:
          destination: https://gitlab.com/roostorg/${{ matrix.repo }}.git
          token: ${{ secrets.GITLAB_TOKEN }}

      - name: Tangled
        uses: ./.mirror-action
        with:
          destination: git@tangled.org:roost.tools/${{ matrix.repo }}
          ssh_private_key: ${{ secrets.TANGLED_SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.TANGLED_KNOWN_HOSTS }}
